---

- name: Install sensu_go_agent_extra_packages
  apt:
    name: "{{ sensu_go_agent_extra_packages }}"
    state: present

- name: Install sensu_go_agent_package
  apt:
    name: "{{ sensu_go_agent_package }}"
    state: present

- name: Enable sensu_go_agent_service
  service:
    name: "{{ sensu_go_agent_service }}"
    enabled: yes

- name: Create /etc/default/sensu-agent
  template:
    src: Debian.default.j2
    dest: /etc/default/sensu-agent
    validate: sh -n %s
  notify:
    - Restart sensu_go_agent

- name: Patch /etc/init.d/sensu-agent
  patch:
    backup: yes
    src: ubuntu.init.patch
    dest: /etc/init.d/sensu-agent
  when:
    - ansible_service_mgr == 'sysvinit'
  notify:
    - Restart sensu_go_agent
