---

- name: Install sensu_go_agent_extra_packages
  yum:
    name: "{{ sensu_go_agent_extra_packages }}"
    state: present

- name: Install sensu_go_agent_package
  yum:
    name: "{{ sensu_go_agent_package }}"
    state: present

- name: Enable sensu_go_agent_service
  service:
    name: "{{ sensu_go_agent_service }}"
    enabled: yes

- name: Create /etc/sysconfig/sensu-agent
  template:
    src: RedHat.sysconfig.j2
    dest: /etc/sysconfig/sensu-agent
    validate: sh -n %s
  notify:
    - Restart sensu_go_agent
