---
# tasks file for ansible-role-sensu_go_agent

- name: "Include {{ ansible_os_family }}.yml"
  include_vars: "{{ ansible_os_family }}.yml"

- name: "Include install-{{ ansible_os_family }}.yml"
  include: "install-{{ ansible_os_family }}.yml"

- name: Create sensu_go_agent_log_dir directory
  file:
    path: "{{ sensu_go_agent_log_dir }}"
    mode: 0755
    owner: "{{ sensu_go_agent_user }}"
    group: "{{ sensu_go_agent_group }}"
    state: directory
  notify: Restart sensu_go_agent

- name: Create sensu_go_agent_cache_dir directory
  file:
    path: "{{ sensu_go_agent_cache_dir }}"
    mode: 0755
    owner: "{{ sensu_go_agent_user }}"
    group: "{{ sensu_go_agent_group }}"
    state: directory
  notify: Restart sensu_go_agent

- name: Create sensu_go_agent_conf_file
  template:
    src: sensu-agent.yml.j2
    dest: "{{ sensu_go_agent_conf_file }}"
    # validate: echo %s
  notify: Restart sensu_go_agent

- name: Configure sensu_go_agent_ruby_plugins
  gem:
    name: "{{ item }}"
    user_install: "{% if sensu_go_agent_use_embedded_ruby %}no{% else %}yes{% endif %}"
    executable: "{% if sensu_go_agent_use_embedded_ruby %}{{ sensu_go_agent_embedded_ruby_gem }}{% else %}{{ ___undefined | default(omit) }}{% endif %}"
  with_items: "{{ sensu_go_agent_ruby_plugins }}"
  become: "{% if sensu_go_agent_use_embedded_ruby %}no{% else %}yes{% endif %}"
  become_user: "{{ sensu_go_agent_user }}"

- name: Start sensu_go_agent
  service:
    name: "{{ sensu_go_agent_service }}"
    state: started
